### ISSUE TITLE
Differences in ml100k, ml1m and documentation.

### ISSUE THREAD

**Issue by smeyerhot** [tohtsky/myFM#2]
It looks as though both notebooks are loosely following the docs but all three are different. Is one example more up to date than the others or are they all intentionally different? Which notebook should readers step through?

**Comment by tohtsky** [comment]
Hello again! The differences are actually intentional.
Since the purpose of the notebook is to pursue accuracy (RMSE), it contains more elaborate features than the docs (but rather tedious).
I wanted users to understand how myFM works with the documentation first, and then look at the notebooks and scripts.
I should have made that clear somewhere, thanks!

**Comment by smeyerhot** [comment]
Ah I see, that’s good to know—thanks! Just so I am clear, the differences between the two notebooks are also intentional? In other words, the 100k vs 1m are different implementations but share some of the same comments. I just wanted to make sure it wasn’t just a matter of one being outdated before stepping through them.

**Comment by tohtsky** [comment]
Their difference too is actually intentional. 
Since ML100k example is more complicated in that it uses user/item's additional information (age, occupation, ...) , it is neater to resort to more advanced API (our encoder utility classes).
ML1m example utilizes simpler (i.e., timeSVD++-like) information, so it is acceptable to use primitive technique.
Note that they differ by how we create the input sparse matrices and they both are completely valid.
Does this answer your question?

**Comment by smeyerhot** [comment]
Awesome, @tohtsky.

That does answer my question. I look forward to stepping through them today!
